# Generated by Django 4.2.26 on 2026-02-03 16:37

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0132_approval_workflow_seed_data'),
        ('nautobot_dns_models', '0006_rename_address_aaaarecord_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSIGKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('algorithm', models.CharField(default='hmac-sha256', max_length=50)),
                ('secret', django_cryptography.fields.encrypt(models.CharField(max_length=500))),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('zones', models.ManyToManyField(blank=True, related_name='tsig_keys', to='nautobot_dns_models.dnszone')),
            ],
            options={
                'verbose_name': 'TSIG Key',
                'verbose_name_plural': 'TSIG Keys',
                'ordering': ['name'],
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ZoneTransferACL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('prefix_length', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(128)])),
                ('action', models.CharField(default='allow', max_length=10)),
                ('priority', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('tsig_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acl_entries', to='nautobot_dns_models.tsigkey')),
                ('zones', models.ManyToManyField(blank=True, related_name='zone_transfer_acls', to='nautobot_dns_models.dnszone')),
            ],
            options={
                'verbose_name': 'Zone Transfer ACL',
                'verbose_name_plural': 'Zone Transfer ACLs',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['priority', 'is_active'], name='acl_priority_active_idx'), models.Index(fields=['action'], name='acl_action_idx'), models.Index(fields=['is_active'], name='acl_is_active_idx')],
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
