# Generated by Django 4.2.26 on 2026-02-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_dns_models', '0007_tsigkey_zonetransferacl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zonetransferacl',
            unique_together={('ip_address', 'prefix_length', 'priority')},
        ),
    ]
